_wandb:
    value:
        cli_version: 0.23.1
        e:
            7ocqkzzt6fpx6p5ysrbuphs3x3fmnq9x:
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "107477987328"
                        used: "100370817024"
                email: hashemi.nazanin@gmail.com
                executable: N:\Master\3\AML\Project\Git\aml-project\.venv_312\Scripts\python.exe
                git:
                    commit: 6aacce984a9569c705df3199699e59be863d62cb
                    remote: https://github.com/SolarFlareZ/aml-project.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-d3fa754d-863f-246d-3d8a-f0461df6d231
                host: Nazanin
                memory:
                    total: "16780513280"
                os: Windows-11-10.0.26200-SP0
                program: -m src.fl-train
                python: CPython 3.13.4
                root: N:\Master\3\AML\Project\Git\aml-project
                startedAt: "2025-12-31T12:44:46.331206Z"
                writerId: 7ocqkzzt6fpx6p5ysrbuphs3x3fmnq9x
        m: []
        python_version: 3.13.4
        t:
            "1":
                - 1
                - 9
                - 41
                - 50
                - 103
            "2":
                - 1
                - 9
                - 41
                - 50
                - 103
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.4
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
data:
    value:
        batch_size: 64
        client_frac: 0.4
        data_dir: ./data
        fl_clients: 5
        fl_rounds: 5
        iid: true
        image_size: 224
        local_epochs: 1
        non_iid_classes: 10
        num_workers: 0
        val_split: 0.1
experiment_name:
    value: fl_task_arithmetic
logging:
    value:
        log_dir: ./results/logs
model:
    value:
        freeze_backbone: true
        image_size: 224
        num_classes: 100
optimizer:
    value:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0005
pruning:
    value:
        sparsity: 0.5
seed:
    value: 42
task_arithmetic:
    value:
        alpha: 0.4
trainer:
    value:
        accelerator: cpu
        devices: 1
        precision: 32
        val_check_interval: 1
