_wandb:
    value:
        cli_version: 0.23.1
        e:
            mtnh41tu9b6l3wvgwulz1tgq0lfng72g:
                args:
                    - trainer.accelerator='gpu'
                    - trainer.devices=1
                    - trainer.precision='16-mixed'
                codePath: src\fl-train.py
                codePathLocal: src\fl-train.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "107477987328"
                        used: "100819496960"
                email: hashemi.nazanin@gmail.com
                executable: N:\Master\3\AML\Project\Git\aml-project\.venv_312\Scripts\python.exe
                git:
                    commit: 6aacce984a9569c705df3199699e59be863d62cb
                    remote: https://github.com/SolarFlareZ/aml-project.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-d3fa754d-863f-246d-3d8a-f0461df6d231
                host: Nazanin
                memory:
                    total: "16780513280"
                os: Windows-11-10.0.26200-SP0
                program: N:\Master\3\AML\Project\Git\aml-project\src\fl-train.py
                python: CPython 3.13.4
                root: N:\Master\3\AML\Project\Git\aml-project
                startedAt: "2026-01-02T09:31:02.726277Z"
                writerId: mtnh41tu9b6l3wvgwulz1tgq0lfng72g
        m: []
        python_version: 3.13.4
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 50
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 50
                - 53
                - 103
            "3":
                - 2
                - 16
            "4": 3.13.4
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
data:
    value:
        batch_size: 32
        client_frac: 0.1
        data_dir: ./data
        fl_clients: 100
        fl_rounds: 500
        iid: true
        image_size: 224
        local_epochs: 3
        non_iid_classes: 10
        num_workers: 0
        val_split: 0.1
experiment_name:
    value: fl_task_arithmetic
logging:
    value:
        log_dir: ./results/logs
model:
    value:
        freeze_backbone: false
        image_size: 224
        num_classes: 100
optimizer:
    value:
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.0005
pruning:
    value:
        num_calibration_rounds: 3
        sparsity: 0.5
seed:
    value: 42
task_arithmetic:
    value:
        alpha: 0.4
trainer:
    value:
        accelerator: gpu
        devices: 1
        precision: 16-mixed
        val_check_interval: 10
