wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.4
    cli_version: 0.23.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1767186454
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 103
      2:
      - 1
      - 9
      - 41
      - 50
      - 103
      3:
      - 2
      - 13
      - 16
      - 37
      - 42
      4: 3.13.4
      5: 0.23.1
      8:
      - 3
      13: windows-amd64
    e:
      w9yd9nyvn2lhx01vlhw9dkvdjwgjtu4x:
        os: Windows-11-10.0.26200-SP0
        python: CPython 3.13.4
        started_at: '2025-12-31T13:07:32.569329Z'
        program: -m src.fl-train
        git:
          remote_url: https://github.com/SolarFlareZ/aml-project.git
          commit: 6aacce984a9569c705df3199699e59be863d62cb
        email: hashemi.nazanin@gmail.com
        root: N:\Master\3\AML\Project\Git\aml-project
        host: Nazanin
        executable: N:\Master\3\AML\Project\Git\aml-project\.venv_312\Scripts\python.exe
        cpu_count: 14
        cpu_count_logical: 20
        gpu_type: NVIDIA GeForce RTX 4050 Laptop GPU
        gpu_count: 1
        disk:
          /:
            total: '107477987328'
            used: '100370882560'
        memory:
          total: '16780513280'
        gpu_nvidia:
        - name: NVIDIA GeForce RTX 4050 Laptop GPU
          memory_total: '6439305216'
          cuda_cores: 2560
          architecture: Ada
          uuid: GPU-d3fa754d-863f-246d-3d8a-f0461df6d231
        cuda_version: '12.7'
        writer_id: w9yd9nyvn2lhx01vlhw9dkvdjwgjtu4x
experiment_name:
  desc: null
  value: fl_task_arithmetic
seed:
  desc: null
  value: 42
data:
  desc: null
  value:
    data_dir: ./data
    batch_size: 32
    num_workers: 0
    val_split: 0.1
    fl_clients: 100
    fl_rounds: 500
    client_frac: 0.1
    local_epochs: 3
    iid: true
    non_iid_classes: 10
    image_size: 224
model:
  desc: null
  value:
    num_classes: 100
    freeze_backbone: false
    image_size: 224
trainer:
  desc: null
  value:
    accelerator: gpu
    devices: 1
    precision: 16-mixed
    val_check_interval: 10
optimizer:
  desc: null
  value:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
task_arithmetic:
  desc: null
  value:
    alpha: 0.4
pruning:
  desc: null
  value:
    sparsity: 0.5
logging:
  desc: null
  value:
    log_dir: ./results/logs
